### ISSUE TITLE
AttributeError: '_OpNamespace' '_C' object has no attribute 'rms_norm'

### ISSUE THREAD

**Issue by jeffyeylw** [openreasoner/openr#28]
### System Info

![image](https://github.com/user-attachments/assets/7ba8301c-d510-435e-9f08-6d2d9d2a6273)
![image](https://github.com/user-attachments/assets/33382392-e057-473b-8dbf-dfbdca46f4ce)

It looks to me a compatible issue between torch and vllm. So I refer to https://github.com/vllm-project/vllm/issues/5804 and tried downgrade the vllm version but same error. I got this error when I tried to run the sh scripts/eval/cot_rerank.sh

My attempts: 
torch 2.4.0 + vllm 0.6.1.post2 + cuda11.8
torch 2.3.0+cu118, vllm 0.5.1 + cuda11.8

Not sure if anyone encounter the same issue. 

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the codebase (such as scrips/, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Manual install torch from https://pytorch.org/get-started/previous-versions/, then pip install vllm, pip install flash_attn from https://github.com/Dao-AILab/flash-attention/releases/
Then proceed to pip install -r requirement.txt and repeat the rest. 

### Expected behavior

Should start inference.

**Comment by jeffyeylw** [comment]
Resolved it by:
# Install vLLM=0.6.1.post1 with CUDA 11.8.
export PYTHON_VERSION=310
pip install https://github.com/vllm-project/vllm/releases/download/v${VLLM_VERSION}/vllm-${VLLM_VERSION}+cu118-cp${PYTHON_VERSION}-cp${PYTHON_VERSION}-manylinux1_x86_64.whl --extra-index-url https://download.pytorch.org/whl/cu118

Intall vllm first then the rest of requirements.

**Comment by GennVa** [comment]
Same issue with vLLM==0.6.4.post1 and torch 2.5.1+cu118

**Comment by jeffyeylw** [comment]
> Same issue with vLLM==0.6.4.post1 and torch 2.5.1+cu118

Did you install vLLM first before installing torch? Installing vLLM will include its corresponding version of torch. If you install torch first coult led to some compatibility issue. It is just my assumption. I was trying out different version of vllm&torch and found this worked for me.

**Comment by GennVa** [comment]
@jeffyeylw I'm installing first torch (2.5.1+cu118) and then  vLLM==0.6.4.post1.

>  was trying out different version of vllm&torch and found this worked for me.

Can you write your versions, please?

From my side, i'm actually using torch 2.4+cu118 and vllm 0.5.5, but it's a bit old.

**Comment by jeffyeylw** [comment]
Attached my versions: 
![image](https://github.com/user-attachments/assets/8d1ba84f-34a4-4545-b3ec-7b33a5381997)
![image](https://github.com/user-attachments/assets/a1e8c533-70a3-4b12-8d14-70aa59807f55)

I suggest you to try in a new environment, install vllm first then torch. As vllm installation will include its compatible torch version.
