### ISSUE TITLE
About the test-time computation experiments on search methods

### ISSUE THREAD

**Issue by ycjing** [openreasoner/openr#29]
Dear OpenR authors,

Thank you very much for the excellent work! Could you please kindly provide more details on how the figure below, illustrating the scaling inference law, was generated? Many thanks!

![image](https://github.com/user-attachments/assets/6e3b3df2-6ec3-43df-b515-e11398837d7f)

Cheers,

**Comment by ziyuwan** [comment]
Hi [ycjing](https://github.com/ycjing),
Sorry for the late reply, thanks for your interest in our project. Can you show us which part you are not clear in this figure? The x-axis or y-axis or different prm-voting methods?

**Comment by ycjing** [comment]
Dear @ziyuwan 

Thank you very much for your response. I appreciate it. I'm very interested in the x-axis and trying to reproduce the diagram. Could you please kindly provide some instructions on how to control the average tokens per question for reproducing this diagram? 

Many thanks!

**Comment by ziyuwan** [comment]
> Dear @ziyuwan
> 
> Thank you very much for your response. I appreciate it. I'm very interested in the x-axis and trying to reproduce the diagram. Could you please kindly provide some instructions on how to control the average tokens per question for reproducing this diagram?
> 
> Many thanks!

In fact, we've made a typo here, the generation budget is not the average number of tokens per question. 1 generation budget means 1 answer for a question. Namely for Best-of-N, the generation budget is the same as N. And for beam search with a max tree width of 4, and beam_size N, the generation budget here is 4N.
