### ISSUE TITLE
Some possible errors in OmegaPRMv2 / omegaprm.py

### ISSUE THREAD

**Issue by FanqingM** [openreasoner/openr#54]
### System Info

same with repo

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the codebase (such as scrips/, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Why there exists that in OmegaPRMv2 / omegaprm.py
# Perform Monte Carlo estimation for s_new
self.monte_carlo_estimation(s_new)

# Perform Monte Carlo estimation for s_new
self.monte_carlo_estimation(s_new)

It occurs two times, Is it supposed to occur only once?
        
        

### Expected behavior

Why there exists that in OmegaPRMv2 / omegaprm.py
# Perform Monte Carlo estimation for s_new
self.monte_carlo_estimation(s_new)

# Perform Monte Carlo estimation for s_new
self.monte_carlo_estimation(s_new)

It occurs two times, Is it supposed to occur only once?

**Comment by iamlilAJ** [comment]
Hi, 

The duplication has been removed.

Thanks for your contribution!
