### ISSUE TITLE
讨论微信群二维码已过期

### ISSUE THREAD

**Issue by Siegfried-qgf** [openreasoner/openr#55]

**Comment by YanSong97** [comment]
Updated! See [this](https://github.com/openreasoner/openr/blob/main/figure/wechat_qrcode.jpg). Thanks for you notification!

**Comment by CzsGit** [comment]
微信群二维码过期了

**Comment by momofive** [comment]
Hello, it's expired again.

**Comment by LGAG** [comment]
请问有新的二维码吗？
