### ISSUE TITLE
How to convert the format of data generated by OmegaPRMv2 into the format of finetune_qwen_single_gpu.py using?

### ISSUE THREAD

**Issue by butterluo** [openreasoner/openr#67]
### System Info

Ubuntu 22.04, Python 3.10

### Who can help?

@mengfn, @gzqaq, @mengfn, @YanSong97, @iamlilAJ

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the codebase (such as scrips/, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

There is no document describing the process of such format converting.

### Expected behavior

There should be some document to describe the process of "how to convert the format of data generated by OmegaPRMv2 into the format of finetune_qwen_single_gpu.py using"

**Comment by iamlilAJ** [comment]
Hi, you may refer to [preprocess readme](https://github.com/openreasoner/openr/tree/main/preprocess).
