### ISSUE TITLE
tree.py文件的_expand_leaf_node()函数存在bug

### ISSUE THREAD

**Issue by zhangyanbo2007** [openreasoner/openr#70]
### System Info

linux-ubuntu

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the codebase (such as scrips/, ...)
- [ ] My own task or dataset (give details below)

### Reproduction
`for act, rs in zip(simulate_env.legal_actions, prms):
    if len(simulate_env.action_history) + 1 != len(rs):
        logger.warning(
            "PRM value length not match with action history. \
                len(prm)={}, len(act_hist)={} s:\n {}\n\na: \n{}\nrs:{}".format(
                len(prms),
                len(simulate_env.action_history),
                text_state,
                act,
                rs,
            )
        )
        # raise RuntimeError("Tokenizer problems")
        child_values.append(0.0)

    if len(rs) == 0:
        logger.warning(
            "Empty PRM value for: \nState: \n{} \naction: \n{}, will be set to 0.0".format(
                text_state, act
            )
        )
        child_values.append(0.0)
    else:
        # prm-last
        child_values.append(rs[-1])
        # # prm-min
        # child_values.append(min(rs))
        # # prob-prm
        # child_values.append(act['prob'])`

   具体而言是这个代码，child_values的结果是是8个值，而非4个值，应该把最上面的child_values.append(0.0)删除

### Expected behavior

`for act, rs in zip(simulate_env.legal_actions, prms):
    if len(simulate_env.action_history) + 1 != len(rs):
        logger.warning(
            "PRM value length not match with action history. \
                len(prm)={}, len(act_hist)={} s:\n {}\n\na: \n{}\nrs:{}".format(
                len(prms),
                len(simulate_env.action_history),
                text_state,
                act,
                rs,
            )
        )
        # raise RuntimeError("Tokenizer problems")

    if len(rs) == 0:
        logger.warning(
            "Empty PRM value for: \nState: \n{} \naction: \n{}, will be set to 0.0".format(
                text_state, act
            )
        )
        child_values.append(0.0)
    else:
        # prm-last
        child_values.append(rs[-1])
        # # prm-min
        # child_values.append(min(rs))
        # # prob-prm
        # child_values.append(act['prob'])`

**Comment by ziyuwan** [comment]
thanks for your suggestion, we will try to fix it

**Comment by ziyuwan** [comment]
Hi @zhangyanbo2007 ,
How frequently does this happen?
