### ISSUE TITLE
Hello, I would like to ask why many questions and answers fail to generate json files for annotating node data, is this related to what parameters or has other effects

### ISSUE THREAD

**Issue by zjrwtx** [openreasoner/openr#72]
### System Info

windows
python 3.10
latest version
cpu

### Who can help?

@mengfn @gzqaq @YanSong97 @iamlilAJ 

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the codebase (such as scrips/, ...)
- [X] My own task or dataset (give details below)

### Reproduction

![image](https://github.com/user-attachments/assets/9a053827-c53d-4700-8c46-7f488ac97c1e)
![image](https://github.com/user-attachments/assets/35a79b37-8d27-49f0-aa1e-765b3b05a8b0)

### Expected behavior

Question and answer data can generate json files annotating node data

**Comment by iamlilAJ** [comment]
Hi, 

Could you please provide more information, like the base model?
I cannot reproduce the problem you encountered.


<img width="1232" alt="Screenshot 2024-12-06 at 19 26 31" src="https://github.com/user-attachments/assets/19cc68bc-3d20-4765-88f0-51c63d74b31c">

**Comment by zjrwtx** [comment]
> Hi,
> 
> Could you please provide more information, like the base model? I cannot reproduce the problem you encountered.
> 
> <img alt="Screenshot 2024-12-06 at 19 26 31" width="1232" src="https://private-user-images.githubusercontent.com/98063079/393230582-19cc68bc-3d20-4765-88f0-51c63d74b31c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0ODY3MTIsIm5iZiI6MTczMzQ4NjQxMiwicGF0aCI6Ii85ODA2MzA3OS8zOTMyMzA1ODItMTljYzY4YmMtM2QyMC00NzY1LTg4ZjAtNTFjNjNkNzRiMzFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDEyMDAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MDViYzIwMzRlNmVlZjNiODFmZTRkYzM5NGNmODhmMzgyZGU3YzQzYWVjZjQ1ZGI3YWFlMTA3NTBkZmE3OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J_HDWmQjhW4mK_gYEwmj7NH6ROW5af2ILQp-HxvkVuE">

@iamlilAJ 

> Hi,
> 
> Could you please provide more information, like the base model? I cannot reproduce the problem you encountered.
> 
> <img alt="Screenshot 2024-12-06 at 19 26 31" width="1232" src="https://private-user-images.githubusercontent.com/98063079/393230582-19cc68bc-3d20-4765-88f0-51c63d74b31c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0ODY3MTIsIm5iZiI6MTczMzQ4NjQxMiwicGF0aCI6Ii85ODA2MzA3OS8zOTMyMzA1ODItMTljYzY4YmMtM2QyMC00NzY1LTg4ZjAtNTFjNjNkNzRiMzFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDEyMDAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MDViYzIwMzRlNmVlZjNiODFmZTRkYzM5NGNmODhmMzgyZGU3YzQzYWVjZjQ1ZGI3YWFlMTA3NTBkZmE3OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J_HDWmQjhW4mK_gYEwmj7NH6ROW5af2ILQp-HxvkVuE">

thanks @iamlilAJ  i use the deepseek-chat and gpt-4omin, most of qa could not got the node data

**Comment by iamlilAJ** [comment]
Hi, 

There are 32 initial rollouts performed for question selection. If the question is too easy (all correct) or too hard (all wrong), then OmegaPRM would not process these questions.  So you may need a suitable pair of question sets and base model. I suggest `Qwen-2.5-Math-7b-Instruct` for the `MATH` dataset.
  
<img width="854" alt="Screenshot 2024-12-06 at 20 10 06" src="https://github.com/user-attachments/assets/d51572a0-c95c-4a78-bffc-96e7aa0d2a72">

**Comment by zjrwtx** [comment]
> Hi,
> 
> There are 32 initial rollouts performed for question selection. If the question is too easy (all correct) or too hard (all wrong), then OmegaPRM would not process these questions. So you may need a suitable pair of question sets and base model. I suggest `Qwen-2.5-Math-7b-Instruct` for the `MATH` dataset.
> 
> <img alt="Screenshot 2024-12-06 at 20 10 06" width="854" src="https://private-user-images.githubusercontent.com/98063079/393241768-d51572a0-c95c-4a78-bffc-96e7aa0d2a72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0ODc1NDEsIm5iZiI6MTczMzQ4NzI0MSwicGF0aCI6Ii85ODA2MzA3OS8zOTMyNDE3NjgtZDUxNTcyYTAtYzk1Yy00YTc4LWJmZmMtOTZlN2FhMGQyYTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDEyMTQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5NDQ2MmM1ZmUzYTZhMDIzMGE3YjJiYjM1ZTYzYjJjMGEyZTQ4MjM5MWYyNzc4ZjcyZjc5NTg2ZDFkNWEzYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UeBvYTYM7PMmI3qmq7oBBiIkqyLnJtTa__5PTEIXKZ8">

yeah,I guess it's the model type that causes this problem,i would try to use other small model,thanks

**Comment by zjrwtx** [comment]
Hello, I have used qwen's small model and your original Q&A data, but I have tested several questions without node data generation:
![image](https://github.com/user-attachments/assets/8c1dcf83-eec1-414a-a793-72f63c2a4025)
![image](https://github.com/user-attachments/assets/cc3e0a52-5847-4c26-b754-42a63d386b84)

**Comment by zjrwtx** [comment]
@iamlilAJ In principle, a small model should make more errors and then generate node data more easily

**Comment by iamlilAJ** [comment]
Hi, Could you please try to use `OmegaPRM_v2`, the version you used is depretiated

**Comment by zjrwtx** [comment]
hey ,it works for me now when i use OmegaPRM_v2

**Comment by zjrwtx** [comment]
but i met some small problem when run OmegaPRM_v2, i fix it and add a new prhttps://github.com/openreasoner/openr/pull/79
<img width="692" alt="505f8c8b8972e4ad335871ef3a312ee" src="https://github.com/user-attachments/assets/26a768c8-fe41-49df-a5c4-ed45c9a5858a">

**Comment by iamlilAJ** [comment]
Hi,

I'm glad to hear that! Thanks for your contribution.

**Comment by zjrwtx** [comment]
> Hi,
> 
> I'm glad to hear that! Thanks for your contribution.

You're welcome. I will probably contribute more to your project in the future, because I am also very interested in the direction and things that this project does
