### ISSUE TITLE
Maybe the true reason MCTS results are worse than COT: the vanilla_mcts code does NOT incorporate the simulation and back-propagation phase。

### ISSUE THREAD

**Issue by Lolo1222** [openreasoner/openr#76]
### System Info

Operating System=Linux
Python version= 3.10
Hardware=Nvidia3090

### Who can help?

@ziyuwan

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the codebase (such as scrips/, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Hi, thanks for your kind open-source work.

After reading and running the source code, I found that in vanila MCTS process, the simulation and back-propagation phase are **NOT** conducted according to this method: https://github.com/openreasoner/openr/blob/831961ed917a54d5eb5a5cf8e5ed217c0924631e/reason/guided_search/tree.py#L330

The following code snippet pertains to the method, and I have incorporated several comments within it.
```python
    def vanila_mcts(
        self,
        simulate_env: Type[CoTEnv],
        num_path: int,
        reward_model_fn: Optional[Callable] = None,
        select_by_prior: bool = False,
    ) -> List[Dict]:
        api_call_completion_tokens = 0
        _, info = simulate_env.reset(update_legal_action=True)
        api_call_completion_tokens += info["api_completion_token"]
        if self.root is None:
            root = LanguageNode(text_state=simulate_env.get_state())
            self._expand_leaf_node(root, simulate_env, reward_model_fn)
            self.root = root

        traj_list = []

        for i_path in range(num_path):
            ######################## @Lolo1222: MCTS Search Start############################
            node = self.root
            env_copy = simulate_env.copy()
            done = False
            while not done:
            ######################## @Lolo1222: Select Phase Start ############################
                if node.visit_count > 0:
                    # @Lolo1222: Never executes since node.visit_count doesn't update during vanila_search
                    action, node = self._select_child(node, env_copy)
                else:
                    if select_by_prior:
                        action, node = self._select_by_prior(node, env_copy)
                    else:
                        # @Lolo1222: Select phase 
                        action, node = self._select_child(node, env_copy)

                env_copy._next_state_terminated = {}
                assert node.last_action == action
                env_copy._next_state_terminated[action] = node.terminated

                _, _, terminated, truncated, info = env_copy.step(
                    action, update_legal_action=node.is_leaf()
                )

                done = terminated or truncated
                ######################## @Lolo1222: Select Phase End############################
                ######################## @Lolo1222: Expand Phase Start############################
                # @Lolo1222: There node.is_leaf() returns always True.
                if not done and node.is_leaf():
                    self._expand_leaf_node(node, env_copy, reward_model_fn)
                ######################## @Lolo1222: Expand Phase End############################
                api_call_completion_tokens += info["api_completion_token"]
                # @Lolo1222: The search phase has finished without simulation and back-propagation phase
                ######################## @Lolo1222: MCTS Search End############################

            # @Lolo1222: the 'else' branch has no effect for search.
            else:
                if node.visit_count > 0:
                    leaf_value = node.value
                else:
                    if self._init_critic_value:
                        leaf_value = node._initial_value
                    else:
                        leaf_value = reward_model_fn(env_copy.get_state()).item()
            node.update_recursive(leaf_value, env_copy.mcts_mode)

            traj_data = {
                "path_idx": i_path,
                "text": env_copy.answer,
                "value": leaf_value,
                "api_completion_tokens": api_call_completion_tokens,
                "tree_completion_tokens": self._completion_tokens,
            }

            traj_list.append(traj_data)

            api_call_completion_tokens = 0

        return traj_list
```

### Expected behavior

The aforementioned represents my interpretation of the code. Is my understanding correct? If so, I plan to commence rewriting the method based on my comprehension of MCTS.

I would appreciate the opportunity to discuss and exchange insights regarding this method.

Eagerly await your prompt response.

**Comment by ziyuwan** [comment]
https://github.com/openreasoner/openr/issues/59
Hi Lolo, you can check this issue first.

**Comment by ziyuwan** [comment]
> MCTS results are worse than COT

can you share your results and configs?

**Comment by Lolo1222** [comment]
Thank you for your prompt response. The back-propagation https://github.com/openreasoner/openr/blob/d869f4f998d55ffe6c84b8092a3d2eb34c7e78c7/reason/guided_search/tree.py#L394
is executed **following the end of the while loop**, implying that it does not function during the MCTS search. Consequently, the node.visit_count remains at 0 and is never updated. 
It is possible that there is a discrepancy in our mutual understanding. Look forward to timely communication with you to clarify any misunderstandings.

**Comment by ziyuwan** [comment]
Yes
This is a very simple version of MCTS. It only backs up values after rolling out to the terminal nodes. You can design your own search process and contribute to our repo.

**Comment by ziyuwan** [comment]
> Perhaps you are suggesting that this approach can generate a complete path to a specific problem, and we can subsequently generate `num_path` paths to determine the most probable path through voting?

Yes, this is a minimal version.

**Comment by Lolo1222** [comment]
I see. Thank you for your patient and detailed response. Additionally, I noticed that the SearchTree class includes the `get_next_action()` and `_simulate()` methods, which appear to be designed for MCTS but are not currently utilized. Do you have any plans to implement the full MCTS algorithm within the next few days?

**Comment by ziyuwan** [comment]
> Do you have any plans to implement the full MCTS algorithm within the next few days?

Yes, we plan to implement it for more complex tasks.
