### ISSUE TITLE
do we hava a plan feature about Rft?

### ISSUE THREAD

**Issue by zjrwtx** [openreasoner/openr#80]
### Feature request

https://openai.com/form/rft-research-program/

### Motivation

Enhance model professionalism: Reinforcement Fine-Tuning (RFT) is designed to optimize models through high-quality task data sets to make the model perform more accurately in complex tasks in a specific domain, thereby elevating the model from "high school level" to "doctoral level expert" capability.

Reduced training data requirements: RFT technology allows developers to fine-tune models using data sets from tens to thousands of high-quality tasks, meaning significant performance gains can be achieved even with limited data (sometimes just a few dozen samples).

Enhanced reasoning: Unlike traditional fine-tuning, reinforcement fine-tuning does not simply make the model "remember the answer", but by training the model to learn to reason in a specific domain, to find the right answer, thereby improving the model's ability to solve similar problems.

### Your contribution

i guess i can cooperate with you guys

**Comment by YanSong97** [comment]
Yes absolutely! We add RFT to our TODO list with high priority! We welcome any form of collaboration!

**Comment by zjrwtx** [comment]
got it,thanks!

**Comment by kargarisaac** [comment]
Is anyone working on this? I'm interested to contribute.
